
---
title: 'Stat 519 Project#1 Preliminary Report'
author: "Your full Name here + your Github address (e.g. Stephen Lee + https://github.com/sauchilee/Stat519) "
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
  word_document: default
fig_height: 3
fig_width: 6 
  
  
---


## Describe your observations (units) and variables of your Data. Input your data set (in .csv format) here. For example:

```{r}
your_data=read.csv(file="https://raw.githubusercontent.com/sauchilee/Stat519/master/Data/iris.csv",
                   header=T)
dim(your_data)
tail(your_data)

```



## The data set of your project should have well defined experimental units (observations) with at least 10 quantitative (i.e., numerical) variables, plus at least 4 categorical variables. One of the categorical variable should have at least 3 levels/groups with at least 30 observations for each level/group.

## State clearly your research objectives and questions clearly.

## Perform EDA (Exploratory Data Analysis) by computing summary statistics and presenting visulizations in: 
  + Enhanced scatterplots, Convex hull, Chi-plot, Bivariate boxplot, Bivariate density estimator, Bubble plot, Scatterplot matrix, 3-D scatterplot, Star plot, Chernoff faces, and
  + R Graphics  

